Add zh_CN i18n Support
Trivernis/spigot-chunkmaster pull request #73
Opened 2020-07-14 14:10 UTC by NPBeta

Add Chinese (zh-CN) language file for built-in language support.

2020-07-14 18:05 UTC, Trivernis commented
I've asked some people to look over it, just to make sure it's correct

2020-07-16 17:33 UTC, Trivernis requested changes
@NPBeta The results of the review by @ed3d3d (twitter handle) I've requested are:

**TASK_SAVE_FAILED:**
switch 错误 to 失败
保存任务时发生错误 ---> 保存任务失败

**TP_ONLY_PLAYER:** Missing Translation
Suggestion: 只有玩家可用这个命令

2020-07-21 03:27 UTC, NPBeta commented
> switch 错误 to 失败
> 保存任务时发生错误 ---> 保存任务失败

I've checked the source text, and decided to make the translation more consistent as following:
For `Failed to xxx`, `Error when xxx`,etc. :
  - Using `xxx 失败`, because errors like this will not provide error details.
For `Exception when xxx: (details)`,etc. :
  - Using `xxx 时发生错误: (details)` to provide`错误`'s details.

2020-07-21 04:39 UTC, Trivernis approved these changes

2020-07-21 04:40 UTC, merged